/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef} from "react";
import { useGLTF, useAnimations, useKeyboardControls } from '@react-three/drei';

import { useFrame } from '@react-three/fiber';
import { Howl } from 'howler'

export function Nunubot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("src/static/models/nunubot.glb");
  const { actions } = useAnimations(animations, group);
  const [, getKeyboardInput] = useKeyboardControls();
  const laughSound = new Howl({
    src: ['src/static/sounds/Nunu/laugh.ogg'],
    volume: 1.0,
  })
  useFrame(() => {
    const { forward, backward, left, right, laugh } = getKeyboardInput();
    actions['nunu_idle01.anm'].play();
    if (forward || backward || left || right) {
      actions['nunu_run01.anm'].play();
    }
    else if (laugh && !laughSound.playing()){
        actions['nunu_skin04_laugh01.anm'].play();
        laughSound.play()
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="SkinnedMesh">
        <group name="skinned_mesh">
          <skinnedMesh
            name="mesh_0"
            geometry={nodes.mesh_0.geometry}
            material={materials.Nunu_Skin04_Mat}
            skeleton={nodes.mesh_0.skeleton}
          />
          <skinnedMesh
            name="mesh_0_1"
            geometry={nodes.mesh_0_1.geometry}
            material={materials.willump}
            skeleton={nodes.mesh_0_1.skeleton}
          />
          <skinnedMesh
            name="mesh_0_2"
            geometry={nodes.mesh_0_2.geometry}
            material={materials.screen}
            skeleton={nodes.mesh_0_2.skeleton}
          />
          <skinnedMesh
            name="mesh_0_3"
            geometry={nodes.mesh_0_3.geometry}
            material={materials.claws_long}
            skeleton={nodes.mesh_0_3.skeleton}
          />
          <skinnedMesh
            name="mesh_0_4"
            geometry={nodes.mesh_0_4.geometry}
            material={materials.face}
            skeleton={nodes.mesh_0_4.skeleton}
          />
          <skinnedMesh
            name="mesh_0_5"
            geometry={nodes.mesh_0_5.geometry}
            material={materials.wheels}
            skeleton={nodes.mesh_0_5.skeleton}
          />
          <skinnedMesh
            name="mesh_0_6"
            geometry={nodes.mesh_0_6.geometry}
            material={materials.tail_recall}
            skeleton={nodes.mesh_0_6.skeleton}
          />
          {/* <skinnedMesh
            name="mesh_0_7"
            geometry={nodes.mesh_0_7.geometry}
            material={materials.recall}
            skeleton={nodes.mesh_0_7.skeleton}
          /> */}
          <skinnedMesh
            name="mesh_0_8"
            geometry={nodes.mesh_0_8.geometry}
            material={materials.tail}
            skeleton={nodes.mesh_0_8.skeleton}
          />
          {/* <skinnedMesh
            name="mesh_0_9"
            geometry={nodes.mesh_0_9.geometry}
            material={materials.snowman}
            skeleton={nodes.mesh_0_9.skeleton}
          /> */}
          <primitive object={nodes.Root} />
          <primitive object={nodes.Root_Wil} />
          <primitive object={nodes.C_Buffbone_Glb_Layout_Loc} />
          <primitive object={nodes.C_Buffbone_Glb_Center_Loc} />
          <primitive object={nodes.Buffbone_Glb_Ground_Loc} />
          <primitive object={nodes.C_Buffbone_Glb_Overhead_Loc} />
          <primitive object={nodes.Buffbone_Glb_Channel_Loc} />
          <primitive object={nodes.Buffbone_Glb_Weapon_1} />
          <primitive object={nodes.L_Buffbone_Glb_Knee_Loc} />
          <primitive object={nodes.R_Buffbone_Glb_Knee_Loc} />
          <primitive object={nodes.Buffbone_Cstm_Healthbar} />
          {/* <primitive object={nodes.Recall_Plug_Base} /> */}
          {/* <primitive object={nodes.Snowman_Root} /> */}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("src/static/models/nunubot.glb");
export default Nunubot;