/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useEffect } from 'react';
import { useGLTF, useAnimations, useKeyboardControls } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

function NunuSnowball(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    'src/static/models/nunu_snowball.glb'
  );
  const { actions } = useAnimations(animations, group);
  const [, getKeyboardInput] = useKeyboardControls();
  const { showSnowball, setShowSnowball } = props;

  useFrame(() => {
    const { forward, backward, leftward, rightward, snowball } =
      getKeyboardInput();
    if ((forward || backward || leftward || rightward) && snowball) {
      setShowSnowball(snowball);
    } else {
      setShowSnowball(false);
    }
  });

  useEffect(() => {
    if (showSnowball) {
      actions['nunusnowball_forward.anm'].reset().fadeIn(0.2).play();
    }
    return () => {
      actions['nunusnowball_forward.anm'].fadeOut(0.2);
    };
  }, [showSnowball, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="SkinnedMesh">
        <group name="skinned_mesh">
          <skinnedMesh
            name="mesh_0"
            geometry={nodes.mesh_0.geometry}
            material={materials.hull}
            skeleton={nodes.mesh_0.skeleton}
          />
          <skinnedMesh
            name="mesh_0_1"
            geometry={nodes.mesh_0_1.geometry}
            material={materials.Nunu_Snowball_Bot_Core_Mat}
            skeleton={nodes.mesh_0_1.skeleton}
          />
          <skinnedMesh
            name="mesh_0_2"
            geometry={nodes.mesh_0_2.geometry}
            material={materials.snowball_screen}
            skeleton={nodes.mesh_0_2.skeleton}
          />
          <primitive object={nodes.Root} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('src/static/models/nunu_snowball.glb');

export default NunuSnowball;
